version: '3.8'

services:
  drupal:
    image: drupal:apache
    container_name: drupal
    ports:
      - "8080:80"
    volumes:
      - ./drupal/modules:/var/www/html/modules
      - ./drupal/themes:/var/www/html/themes
      - ./drupal/profiles:/var/www/html/profiles
      - ./drupal/sites:/var/www/html/sites
    # - ./drupal/translations:/var/www/html/sites/default/files/translations
    #- ./drupal/:/var/www/html
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USER=drupal
      - DRUPAL_DATABASE_PASSWORD=drupal
    depends_on:
      - mariadb
    restart: unless-stopped
    user: "www-data:www-data"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: unless-stopped

